---
extends: default

rules:
  # 80 chars should be enough, but don't fail if a line is longer
  line-length:
    max: 120
    level: warning

  # Accept both styles for truthy values
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'True', 'False', 'YES', 'NO']

  # Don't force truthy values to be quoted
  quoted-strings:
    required: only-when-needed

  # don't require a space before comments
  comments:
    min-spaces-from-content: 1

  # Don't be too picky about comment formatting
  comments-indentation: disable

  # Allow for blocks when appropriate
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  # Allow missing document start in more places
  document-start:
    level: warning