version: '3.8'

services:
  mariadb:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-secure_password}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-app_db}
      MARIADB_USER: ${MARIADB_USER:-app_user}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-app_password}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./config/custom.cnf:/etc/mysql/mariadb.conf.d/99-custom.cnf:ro
    healthcheck:
      test: ["CMD", "mariadb", "-u$${MARIADB_USER}", "-p$${MARIADB_PASSWORD}", "-e", "SELECT 1;"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - backend

  # Optional: Add a web-based database administration tool
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      UPLOAD_LIMIT: 64M
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mariadb_data:
    driver: local