---
version: '3.8'

services:
  mariadb:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-secure_password}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-app_db}
      MARIADB_USER: ${MARIADB_USER:-app_user}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-app_password}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./config/custom.cnf:/etc/mysql/mariadb.conf.d/99-custom.cnf:ro
    healthcheck:
      test: ["CMD", "mariadb", "-u$${MARIADB_USER}", "-p$${MARIADB_PASSWORD}",
             "-e", "SELECT 1;"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - backend

  # Optional: Add a web-based database administration tool
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      UPLOAD_LIMIT: 64M
    networks:
      - backend

  # Test replication setup
  test-replication:
    build:
      context: .
      dockerfile: tests/Dockerfile.test
    profiles: ["test"]
    depends_on:
      - mariadb-primary
      - mariadb-replica
    command: >
      /bin/bash -c "
        sleep 30 &&
        /tests/helpers/test_replication.sh mariadb-primary 3306 mariadb-replica 3306 root secure_password
      "
    networks:
      - backend

  # Primary instance for replication tests
  mariadb-primary:
    build:
      context: .
      dockerfile: Dockerfile
    profiles: ["test"]
    restart: always
    ports:
      - "3307:3306"
    environment:
      MARIADB_ROOT_PASSWORD: secure_password
      MARIADB_DATABASE: app_db
      MARIADB_USER: app_user
      MARIADB_PASSWORD: app_password
      # Replication-specific settings
      MARIADB_REPLICATION_MODE: master
      MARIADB_REPLICATION_USER: replicator
      MARIADB_REPLICATION_PASSWORD: replpass
    volumes:
      - primary_data:/var/lib/mysql
      - ./tests/config/primary.cnf:/etc/mysql/mariadb.conf.d/99-replication.cnf:ro
    healthcheck:
      test: ["CMD", "mariadb", "-uroot", "-psecure_password", "-e", "SELECT 1;"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - backend

  # Replica instance for replication tests
  mariadb-replica:
    build:
      context: .
      dockerfile: Dockerfile
    profiles: ["test"]
    restart: always
    ports:
      - "3308:3306"
    depends_on:
      - mariadb-primary
    environment:
      MARIADB_ROOT_PASSWORD: secure_password
      MARIADB_DATABASE: app_db
      MARIADB_USER: app_user
      MARIADB_PASSWORD: app_password
      # Replication-specific settings
      MARIADB_REPLICATION_MODE: slave
      MARIADB_REPLICATION_USER: replicator
      MARIADB_REPLICATION_PASSWORD: replpass
      MARIADB_MASTER_HOST: mariadb-primary
      MARIADB_MASTER_PORT: 3306
      MARIADB_MASTER_ROOT_PASSWORD: secure_password
    volumes:
      - replica_data:/var/lib/mysql
      - ./tests/config/replica.cnf:/etc/mysql/mariadb.conf.d/99-replication.cnf:ro
    healthcheck:
      test: ["CMD", "mariadb", "-uroot", "-psecure_password", "-e", "SELECT 1;"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  primary_data:
    driver: local
  replica_data:
    driver: local