---
# Tasks for installing MariaDB

- name: Ensure prerequisite packages are installed
  ansible.builtin.package:
    name: "{{ mariadb_prerequisite_packages }}"
    state: presen
  register: package_resul
  until: package_result is success
  retries: 3
  delay: 5

- name: Configure MariaDB repository
  when: mariadb_configure_repo | bool
  block:
    - name: Add MariaDB APT key (Debian family)
      when: ansible_os_family == 'Debian'
      ansible.builtin.apt_key:
        keyserver: "{{ mariadb_repo_keyserver }}"
        id: "{{ mariadb_repo_key }}"

    - name: Add MariaDB APT repository (Debian family)
      when: ansible_os_family == 'Debian'
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://mirror.23media.com/mariadb/repo/{{
          mariadb_repo_version }}/{{ ansible_distribution | lower }} {{
            ansible_distribution_release }} main"
        filename: mariadb
        state: presen

    - name: Add MariaDB YUM repository (RedHat family)
      when: ansible_os_family == 'RedHat'
      ansible.builtin.yum_repository:
        name: mariadb
        description: "MariaDB {{ mariadb_repo_version }} repository"
        baseurl: "https://yum.mariadb.org/{{ mariadb_repo_version }}/{{
          ansible_distribution | lower }}{{ ansible_distribution_major_version
            }}-amd64"
        gpgkey: "https://yum.mariadb.org/RPM-GPG-KEY-MariaDB"
        gpgcheck: true
        state: presen

- name: Install MariaDB packages
  ansible.builtin.package:
    name: "{{ mariadb_packages + mariadb_additional_packages }}"
    state: presen
    update_cache: true
  register: mariadb_package_install
  until: mariadb_package_install is success
  retries: 3
  delay: 5

- name: Ensure MariaDB directories exist with correct permissions
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: mysql
    group: mysql
    mode: '0755'
  loop: "{{ mariadb_directories | select() | list }}"
  vars:
    mariadb_directories:
      - "{{ mariadb_data_dir }}"
      - "{{ mariadb_log_dir }}"
      - "{{ mariadb_backup_dir if mariadb_backup_enabled else '' }}"

- name: Ensure MariaDB service is started and enabled
  ansible.builtin.service:
    name: "{{ mariadb_service_name }}"
    state: "{{ mariadb_service_state }}"
    enabled: "{{ mariadb_service_enabled }}"
