---
# Main task orchestration for MariaDB role

- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
        - "main.yml"
      paths:
        - "{{ role_path }}/vars"
  tags: [always]

- name: Validate required variables
  ansible.builtin.import_tasks: validate.yml
  tags: [validate, always]

- name: Setup MariaDB
  when: mariadb_enabled | bool
  block:
    - name: Install MariaDB
      ansible.builtin.import_tasks: install.yml
      tags: [mariadb, install]

    - name: Configure MariaDB server
      ansible.builtin.import_tasks: configure.yml
      tags: [mariadb, configure]

    - name: Secure MariaDB installation
      ansible.builtin.import_tasks: secure.yml
      when: mariadb_secure_installation | bool
      tags: [mariadb, secure]

    - name: Configure MariaDB users
      ansible.builtin.import_tasks: users.yml
      when: mariadb_users | length > 0
      tags: [mariadb, users]

    - name: Configure MariaDB databases
      ansible.builtin.import_tasks: databases.yml
      when: mariadb_databases | length > 0
      tags: [mariadb, databases]

    - name: Configure MariaDB replication
      ansible.builtin.import_tasks: replication.yml
      when: mariadb_replication_enabled | bool
      tags: [mariadb, replication]

    - name: Configure MariaDB backups
      ansible.builtin.import_tasks: backup.yml
      when: mariadb_backup_enabled | bool
      tags: [mariadb, backup]

    - name: Configure MariaDB monitoring
      ansible.builtin.import_tasks: monitoring.yml
      when: mariadb_monitoring_enabled | bool
      tags: [mariadb, monitoring]
