---
# Main task orchestration for MariaDB role

- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "main.yml"
  tags: [always]

- name: Validate required variables
  include_tasks: validate.yml
  tags: [validate, always]

- name: Ensure MariaDB is installed
  include_tasks: install.yml
  when: mariadb_enabled | bool
  tags: [mariadb, install]

- name: Configure MariaDB server
  include_tasks: configure.yml
  when: mariadb_enabled | bool
  tags: [mariadb, configure]

- name: Secure MariaDB installation
  include_tasks: secure.yml
  when: mariadb_enabled | bool and mariadb_secure_installation | bool
  tags: [mariadb, secure]

- name: Configure MariaDB users
  include_tasks: users.yml
  when: mariadb_enabled | bool and mariadb_users | length > 0
  tags: [mariadb, users]

- name: Configure MariaDB databases
  include_tasks: databases.yml
  when: mariadb_enabled | bool and mariadb_databases | length > 0
  tags: [mariadb, databases]

- name: Configure MariaDB replication
  include_tasks: replication.yml
  when: mariadb_enabled | bool and mariadb_replication_enabled | bool
  tags: [mariadb, replication]

- name: Configure MariaDB backups
  include_tasks: backup.yml
  when: mariadb_enabled | bool and mariadb_backup_enabled | bool
  tags: [mariadb, backup]

- name: Configure MariaDB monitoring
  include_tasks: monitoring.yml
  when: mariadb_enabled | bool and mariadb_monitoring_enabled | bool
  tags: [mariadb, monitoring]
