---
# Tasks for configuring MariaDB monitoring

- name: Create monitoring user
  community.mysql.mysql_user:
    name: "{{ mariadb_monitoring_user }}"
    password: "{{ mariadb_monitoring_password }}"
    host: "{{ mariadb_monitoring_host }}"
    priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT"
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"
  no_log: true
  when: mariadb_monitoring_enabled | bool
  tags: [mariadb, monitoring]

- name: Install Prometheus MySQL exporter
  when: mariadb_exporter_enabled | bool
  tags: [mariadb, monitoring, prometheus]
  block:
    - name: Download MySQL exporter
      ansible.builtin.get_url:
        url: >-
          https://github.com/prometheus/mysqld_exporter/releases/download/v{{ mariadb_exporter_version }}/
          mysqld_exporter-{{ mariadb_exporter_version }}.linux-amd64.tar.gz
        dest: "/tmp/mysqld_exporter-{{ mariadb_exporter_version }}.linux-amd64.tar.gz"
        mode: '0644'
      register: mysqld_exporter_download

    - name: Extract MySQL exporter
      ansible.builtin.unarchive:
        src: "/tmp/mysqld_exporter-{{ mariadb_exporter_version }}.linux-amd64.tar.gz"
        dest: "/tmp"
        remote_src: true
      when: mysqld_exporter_download.changed

    - name: Move MySQL exporter binary to /usr/local/bin
      ansible.builtin.copy:
        src: "/tmp/mysqld_exporter-{{ mariadb_exporter_version }}.linux-amd64/mysqld_exporter"
        dest: "/usr/local/bin/mysqld_exporter"
        mode: '0755'
        remote_src: true
      when: mysqld_exporter_download.changed

    - name: Create system user for MySQL exporter
      ansible.builtin.user:
        name: mysql-exporter
        shell: /bin/false
        system: true
        home: /nonexistent
        create_home: false
        state: present

    - name: Create MySQL exporter configuration
      ansible.builtin.template:
        src: monitoring.conf.j2
        dest: /etc/mysqld_exporter.cnf
        owner: mysql-exporter
        group: mysql-exporter
        mode: '0600'
      notify: restart mysql exporter

    - name: Create MySQL exporter credentials file
      ansible.builtin.template:
        src: mysql_exporter.my.cnf.j2
        dest: /etc/mysql_exporter.my.cnf
        owner: mysql-exporter
        group: mysql-exporter
        mode: '0600'
      notify: restart mysql exporter

    - name: Create systemd service for MySQL exporter
      ansible.builtin.template:
        src: mysqld_exporter.service.j2
        dest: /etc/systemd/system/mysqld_exporter.service
        owner: root
        group: root
        mode: '0644'
      notify: restart mysql exporter

    - name: Ensure MySQL exporter service is enabled and started
      ansible.builtin.systemd:
        name: mysqld_exporter
        state: started
        enabled: true
        daemon_reload: true
  rescue:
    - name: Cleanup MySQL exporter download
      ansible.builtin.file:
        path: "/tmp/mysqld_exporter-{{ mariadb_exporter_version }}.linux-amd64.tar.gz"
        state: absent
  always:
    - name: Ensure MySQL exporter service is stopped
      ansible.builtin.systemd:
        name: mysqld_exporter
        state: stopped

- name: Install MariaDB status check script
  ansible.builtin.template:
    src: mariadb_monitoring.sh.j2
    dest: /usr/local/bin/mariadb_monitoring.sh
    mode: '0755'
    owner: root
    group: root
  tags: [mariadb, monitoring]

- name: Configure monitoring check cron job
  ansible.builtin.cron:
    name: "MariaDB monitoring check"
    job: "/usr/local/bin/mariadb_monitoring.sh > /var/log/mariadb_monitoring.log 2>&1"
    user: root
    minute: "*/5"
    state: present
  tags: [mariadb, monitoring, cron]