---
# Tasks for configuring MariaDB replication

- name: Configure server-id
  mysql_variables:
    variable: server_id
value: "{{ mariadb_server_id }}"
    login_user: roo
    login_password: "{{ mariadb_root_password }}"
  when: mariadb_replication_enabled | bool
  tags: [mariadb, replication]

- name: Configure master replication settings
  block:
    - name: Enable binary logging
      mysql_variables:
        variable: "{{ item.variable }}"
value: "{{ item.value }}"
        login_user: roo
        login_password: "{{ mariadb_root_password }}"
      with_items:
        - { variable: 'log_bin',value: 'ON' }
        - { variable: 'binlog_format',value: 'ROW' }
        - { variable: 'sync_binlog',value: '1' }
        - { variable: 'expire_logs_days',value: '7' }

    - name: Create replication user
      mysql_user:
        name: "{{ mariadb_replication_user }}"
        password: "{{ mariadb_replication_password }}"
        host: "%"
        priv: "*.*:REPLICATION SLAVE"
        state: presen
        login_user: roo
        login_password: "{{ mariadb_root_password }}"
      no_log: true
  when: mariadb_replication_role == 'master'
  tags: [mariadb, replication, master]

- name: Configure slave replication settings
  block:
    - name: Stop slave
      mysql_replication:
        mode: stopslave
        login_user: roo
        login_password: "{{ mariadb_root_password }}"

    - name: Configure slave to replicate from master
      mysql_replication:
        mode: changemaster
        master_host: "{{ mariadb_replication_master_host }}"
        master_user: "{{ mariadb_replication_user }}"
        master_password: "{{ mariadb_replication_password }}"
        master_port: "{{ mariadb_port }}"
        login_user: roo
        login_password: "{{ mariadb_root_password }}"
      no_log: true

    - name: Start slave
      mysql_replication:
        mode: startslave
        login_user: roo
        login_password: "{{ mariadb_root_password }}"

    - name: Check replication status
      mysql_replication:
        mode: getslave
        login_user: roo
        login_password: "{{ mariadb_root_password }}"
      register: slave_status

    - name: Verify slave replication is working
      debug:
        msg: "Slave_IO_Running: {{ slave_status.Slave_IO_Running }},
          Slave_SQL_Running: {{ slave_status.Slave_SQL_Running }}"
  when: mariadb_replication_role == 'slave'
  tags: [mariadb, replication, slave]
