---
# Tasks for securing MariaDB installation

- name: Set root password
  community.mysql.mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mariadb_root_password }}"
    login_unix_socket: "{{ mariadb_socket }}"
    state: present
  with_items:
    - localhost
    - 127.0.0.1
    - ::1
    - "{{ ansible_hostname }}"
  register: root_password
  no_log: true
  when: mariadb_root_password != ""

- name: Create .my.cnf file for root
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: '0600'
  no_log: true
  when: mariadb_root_password != ""

- name: Remove anonymous users
  community.mysql.mysql_user:
    name: ''
    host_all: true
    state: absent
    login_user: root
    login_password: "{{ mariadb_root_password }}"
  when: mariadb_remove_anonymous_users | bool
  no_log: true

- name: Remove test database
  community.mysql.mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mariadb_root_password }}"
  when: mariadb_remove_test_database | bool
  no_log: true

- name: Disallow root login remotely
  community.mysql.mysql_user:
    name: root
    host: "{{ item }}"
    state: absent
    login_user: root
    login_password: "{{ mariadb_root_password }}"
  with_items:
    - "{{ ansible_hostname }}"
    - "%"
  when: mariadb_disallow_root_login_remotely | bool
  no_log: true

- name: Configure password validation plugin
  community.mysql.mysql_query:
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    query: "INSTALL PLUGIN validate_password SONAME 'validate_password.so';"
  no_log: true
  register: validate_plugin
  failed_when: >
    validate_plugin.failed and
    'already exists' not in validate_plugin.msg|default('')

- name: Set password validation policy
  community.mysql.mysql_query:
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    query: "SET GLOBAL validate_password_policy = 'STRONG';"
  no_log: true
  register: set_policy
  failed_when: >
    set_policy.failed and
    'Unknown system variable' not in set_policy.msg|default('')