---
- name: Converge
  hosts: all
  become: true
  vars:
    mariadb_root_password: "molecule_test_password"
    mariadb_databases:
      - name: monitoring_test_db
        encoding: utf8mb4
        collation: utf8mb4_unicode_ci
    mariadb_users:
      - name: monitoring_test_user
        password: monitoring_test_password
        priv: "monitoring_test_db.*:ALL"
    mariadb_monitoring_enabled: true
    mariadb_monitoring_user: "mysql_exporter"
    mariadb_monitoring_password: "exporter_password"
    mariadb_exporter_enabled: true
    mariadb_exporter_port: 9104
  roles:
    - role: thomasvincent.mariadb