---
# Handlers for MariaDB role

- name: restart mariadb
  service:
    name: "{{ mariadb_service_name }}"
    state: restarted
  listen: "restart mariadb"

- name: reload mariadb
  service:
    name: "{{ mariadb_service_name }}"
    state: reloaded
  listen: "reload mariadb"

- name: restart mysql exporter
  systemd:
    name: mysqld_exporter
    state: restarted
  listen: "restart mysql exporter"
