---
# Handlers for MariaDB role

- name: restart mariadb
  ansible.builtin.service:
    name: "{{ mariadb_service_name }}"
    state: restarted
  listen: "restart mariadb"

- name: reload mariadb
  ansible.builtin.service:
    name: "{{ mariadb_service_name }}"
    state: reloaded
  listen: "reload mariadb"

- name: restart mysql exporter
  ansible.builtin.systemd:
    name: mysqld_exporter
    state: restarted
    daemon_reload: true
  listen: "restart mysql exporter"
