---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: primary
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    exposed_ports:
      - "3306"
    networks:
      - name: mariadb_replication
    groups:
      - primary

  - name: replica
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    exposed_ports:
      - "3306"
    networks:
      - name: mariadb_replication
    groups:
      - replica

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_enabled: profile_tasks, timer, yaml
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  inventory:
    group_vars:
      all:
        mariadb_root_password: "molecule_test_password"
        mariadb_databases:
          - name: replication_test_db
            encoding: utf8mb4
            collation: utf8mb4_unicode_ci
        mariadb_users:
          - name: replication_test_user
            password: replication_test_password
            priv: "replication_test_db.*:ALL"
        mariadb_replication_enabled: true
        mariadb_replication_user: replicator
        mariadb_replication_password: replication_password
      primary:
        mariadb_bind_address: "0.0.0.0"
        mariadb_version: "${MOLECULE_MARIADB_VERSION:-10.6}"
        mariadb_replication_role: master
        mariadb_server_id: 1
      replica:
        mariadb_bind_address: "0.0.0.0"
        mariadb_version: "${MOLECULE_MARIADB_VERSION:-10.6}"
        mariadb_replication_role: slave
        mariadb_replication_master_host: primary
        mariadb_server_id: 2
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint --profile min