---
name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/pull_request_template.md'
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 7 * * 1'  # Run every Monday at 7 AM UTC
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Lint workflow files
        uses: reviewdog/action-yamllint@v1.21.0 # Latest version
        
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install ansible-lint yamllint

      - name: Run yamllint
        run: yamllint .

      - name: Run ansible-lint
        run: ansible-lint --profile production