name: Release

on:
  push:
    tags:
      - "v*" # Matches tags like v1.0.0, v2.1.3, etc.

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    permissions:
      contents: write # Required for creating releases

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4.1.2 # Latest as of March 2025
        with:
          fetch-depth: 0 # Needed for changelog generation

      - name: Lint workflow files
        uses: reviewdog/action-yamllint@v1.10.0 # Latest version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          yamllint_flags: "--strict"

      - name: Generate Changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.3.1 # Latest version
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Tag Name
        id: tag_name
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
          # Validate tag format (semantic versioning)
          if [[ ! "${TAG_NAME}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Tag ${TAG_NAME} doesn't follow semantic versioning (vX.Y.Z)"
            exit 1
          fi

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2.0.4 # Latest version
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          body: |
            ## Changes
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
          commitish: ${{ github.sha }}
