---
---
---
name: CI

# GitHub Actions workflow trigger
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 7 * * 1'  # Run every Monday at 7:00 UTC

jobs:
  lint:
    name: Lin
    runs-on: ubuntu-lates
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-lint yamllin

      - name: Run yamllin
        run: yamllint .

      - name: Run ansible-lin
        run: ansible-lin

  test:
    name: Tes
    runs-on: ubuntu-lates
    strategy:
      matrix:
        distro:
          - ubuntu2004
          - ubuntu2204
          - debian11
          - debian12
          - centos7
          - rockylinux8

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible molecule molecule-docker docker pytest pytest-
            testinfra

      - name: Run Molecule tests
        run: |
          cd ../
          mv ansible-role-mariadb mariadb
          cd mariadb
          molecule tes
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
